name: CI/CD
on: push

jobs:
  setup_flutter_and_java:
    name: Setup Flutter and Java JDK
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
      - run: echo "${RUNNER_TEMP}/flutter/bin" ${RUNNER_TEMP}/flutter/.pub-cache/bin  >> $GITHUB_PATH
      - name: Set up Java JDK
        uses: actions/setup-java@v1
        with:
          java-version: 'x.x'
          
  flutter_test:
    name: Run Flutter app tests
    runs-on: windows-latest
    needs: setup_flutter_and_java
    steps :
      - run: flutter pub global activate melos && flutter pub global run melos build:clean
      - run: dart format . 
      - run: melos test               
