name: CI/CD
on: push

jobs:
  setup_melos:
    name: Activate Melos
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-
      - uses: subosito/flutter-action@v2
      - run: flutter pub global activate melos
