name : Variables
on: push

jobs:
  setup:
    runs-on: windows-latest
    steps:
         - run: echo username ${{vars.USERNAME}} 
         - run: echo ubi token ${{vars.UBITOKEN}} 
         - run: echo token ${{vars.TOKEN}} 
