name: Build and Deploy APKs
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
#       with:
#         flutter-version: 2.x
        
    - name: Install dependencies and generate code
      run: |
        echo "run"
        # melos bootstrap
        # melos generate
        
    - name: Build APKs
      run: melos build:apk:qa
      
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: app-release
        path: packages/**/build/app/outputs/flutter-apk/app-qa-release.apk
        
    - name: Set execute permissions for deploy.sh
      run: chmod +x test.sh

    - name: Run test deploy script
      run: ./test.sh
      shell: bash
