name : Variables
on: push

jobs:
  setup:
    runs-on: windows-latest
    steps:
         - run: echo username ${{secrets[NEXUS_PASSWORD]}} 
         - run: echo username ${{secrets[env.NEXUS_PASSWORD]}} 

